import { Inter  } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import MainLayout from "@/components/layouts/MainLayout";
import { GlobalStyle } from "./style";

const inter = Inter({ subsets: ["latin"]  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MainLayout>
            <GlobalStyle />
            {children}
          </MainLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
